apiVersion: apps/v1
Kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  templates:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: thiagogonncalves/conversao-temperatura:v1
        ports:
        - containersPort: 80
---
apiVersion: v1
Kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: web
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30000
  type: NodePort